document.writeln("	<div class=\'container\'>");
document.writeln("		<div class=\'row\'>");
document.writeln("			<div class=\'col-lg-3\'>");
document.writeln("				<div class=\'widget\'>");
document.writeln("					<h5 class=\'widgetheading\'>联系我们</h5>");
document.writeln("					<address>");
document.writeln("					<strong>上海交通大学智能电网大楼323室</strong><br>");
document.writeln("					 上海市闵行区东川路800号</address>");
document.writeln("					<p>");
document.writeln("						<i class=\'icon-phone\'></i> 54749110 <br>");
document.writeln("						<i class=\'icon-envelope-alt\'></i> changyue@sjtu.edu.cn			</p>");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("	  </div>");
document.writeln("	</div>");