document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("<head>");
document.writeln("<meta charset=\'utf-8\'>");
document.writeln("<title>LAB323</title>");
document.writeln("<meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\' />");
document.writeln("<meta name=\'description\' content=\'\' />");
document.writeln("<!-- css -->");
document.writeln("<link href=\'css/bootstrap.min.css\' rel=\'stylesheet\' />");
document.writeln("<link href=\'css/fancybox/jquery.fancybox.css\' rel=\'stylesheet\'>");
document.writeln("<link href=\'css/jcarousel.css\' rel=\'stylesheet\' />");
document.writeln("<link href=\'css/flexslider.css\' rel=\'stylesheet\' />");
document.writeln("<link href=\'css/style.css\' rel=\'stylesheet\' />");
document.writeln("");
document.writeln("");
document.writeln("<!-- Theme skin -->");
document.writeln("<link href=\'skins/default.css\' rel=\'stylesheet\' />");
document.writeln("");
document.writeln("<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->");
document.writeln("<!--[if lt IE 9]>");
document.writeln("      <script src=\'http://html5shim.googlecode.com/svn/trunk/html5.js\'></script>");
document.writeln("    <![endif]-->");
document.writeln("");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div id=\'wrapper\'>");
document.writeln("	<!-- start header -->");
document.writeln("	<header>");
document.writeln("        <div class=\'navbar navbar-default navbar-static-top\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <div class=\'navbar-header\'>");
document.writeln("                    <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'.navbar-collapse\'>");
document.writeln("                        <span class=\'icon-bar\'></span>");
document.writeln("                        <span class=\'icon-bar\'></span>");
document.writeln("                        <span class=\'icon-bar\'></span>");
document.writeln("                    </button>");
document.writeln("                    <a class=\'navbar-brand\' href=\'index.html\'><span>LAB323</span></a>");
document.writeln("                </div>");
document.writeln("                <div class=\'navbar-collapse collapse \'>");
document.writeln("                    <ul class=\'nav navbar-nav\'>");
document.writeln("                        <li class=\'active\'><a href=\'index.html\'>主页</a></li>");
document.writeln("                        <li class=\'dropdown\'>");
document.writeln("                            <a href=\'#\' class=\'dropdown-toggle \' data-toggle=\'dropdown\' data-hover=\'dropdown\' data-delay=\'0\' data-close-others=\'false\'>主要产品 <b class=\' icon-angle-down\'></b></a>");
document.writeln("                            <ul class=\'dropdown-menu\'>");
document.writeln("                                <li><a href=\'power.html\'>电源</a></li>");
document.writeln("                                <li><a href=\'in_converter.html\'>变频变换器</a></li>");
document.writeln("								<li><a href=\'monitor.html\'>监测控制系统</a></li>");
document.writeln("                                <li><a href=\'others.html\'>其他</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li><a href=\'aboutus.html\'>简介</a></li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("	</header>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");