document.writeln("<div class=\'col-lg-4\'>");
document.writeln("	<aside class=\'right-sidebar\'>");
document.writeln("	<div class=\'widget\'>");
document.writeln("		<h5 class=\'widgetheading\'>主要产品</h5>");
document.writeln("		<ul class=\'cat\'>");
document.writeln("			<li><i class=\'icon-angle-right\'></i><a href=\'power.html\'>电源</a><span> (20)</span></li>");
document.writeln("			<li><i class=\'icon-angle-right\'></i><a href=\'in_converter.html\'>变频变换器</a><span> (11)</span></li>");
document.writeln("			<li><i class=\'icon-angle-right\'></i><a href=\'monitor.html\'>监测控制系统</a><span> (9)</span></li>");
document.writeln("			<li><i class=\'icon-angle-right\'></i><a href=\'others.html\'>其他</a><span> (12)</span></li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("	<div class=\'widget\'>");
document.writeln("		<h5 class=\'widgetheading\'>最新产品</h5>");
document.writeln("		<ul class=\'recent\'>");
document.writeln("			<li>");
document.writeln("			<img src=\'img/dummies/blog/65x65/thumb1.jpg\' class=\'pull-left\' alt=\'\' />");
document.writeln("			<h6><a href=\'#\'>Lorem ipsum dolor sit</a></h6>");
document.writeln("			<p>");
document.writeln("				 Mazim alienum appellantur eu cu ullum officiis pro pri						</p>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("			<a href=\'#\'><img src=\'img/dummies/blog/65x65/thumb2.jpg\' class=\'pull-left\' alt=\'\' /></a>");
document.writeln("			<h6><a href=\'#\'>Maiorum ponderum eum</a></h6>");
document.writeln("			<p>");
document.writeln("				 Mazim alienum appellantur eu cu ullum officiis pro pri						</p>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("			<a href=\'#\'><img src=\'img/dummies/blog/65x65/thumb3.jpg\' class=\'pull-left\' alt=\'\' /></a>");
document.writeln("			<h6><a href=\'#\'>Et mei iusto dolorum</a></h6>");
document.writeln("			<p>");
document.writeln("				 Mazim alienum appellantur eu cu ullum officiis pro pri						</p>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("	</aside>");
document.writeln("</div>");